CREATE DATABASE hostel_db;
USE hostel_db;
CREATE TABLE students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    room VARCHAR(20),
    course VARCHAR(100),
    phone VARCHAR(20),
    fees VARCHAR(20),
    status VARCHAR(20)
);
CREATE TABLE rooms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    number VARCHAR(20),
    type VARCHAR(50),
    status VARCHAR(20),
    occupant VARCHAR(100)
);
CREATE TABLE complaints (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200),
    room VARCHAR(20),
    description TEXT,
    priority VARCHAR(20),
    student VARCHAR(100),
    status VARCHAR(20)
);
CREATE TABLE payments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student VARCHAR(100),
    amount INT,
    payment_date DATE,
    status VARCHAR(20)
);
INSERT INTO rooms (number, type, status)
SELECT CONCAT(100 + n, '-A'), 'Single', 'vacant'
FROM (
SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) numbers;
INSERT INTO rooms (number, type, status)
SELECT CONCAT(200 + n, '-B'), 'Double', 'vacant'
FROM (
SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28
) numbers;
INSERT INTO rooms (number, type, status)
SELECT CONCAT(300 + n, '-C'), 'Triple', 'vacant'
FROM (
SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5
UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
UNION SELECT 21 UNION SELECT 22
) numbers;
INSERT INTO rooms (number, type, status)
SELECT CONCAT(400 + n, '-D'), 'Suite', 'vacant'
FROM (
SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4
UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8
UNION SELECT 9 UNION SELECT 10 UNION SELECT 11 UNION SELECT 12
UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16
) numbers;
INSERT INTO payments (student, amount, payment_date, status)
VALUES
('Rahul Kumar', 12000, '2026-03-01', 'paid'),
('Priya Mehta', 12500, '2026-03-02', 'paid'),
('Arjun Sharma', 12000, '2026-03-05', 'pending'),
('Neha Patel', 12000, '2026-02-28', 'overdue');

select * from students;
